name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # 알맞은 Ruby 버전
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages