name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push될 때마다 실행

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # 또는 Gemfile에 맞는 버전

      - name: Install dependencies
        run: |
          bundle install

      - name: Build site with Jekyll
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          enable_jekyll: true